package router

import (
	"octo-agent/backend/internal/controller"
	"octo-agent/backend/internal/middleware"

	"github.com/gin-gonic/gin"
)

func RegisterAutomation(rg *gin.RouterGroup, c *controller.AutomationController) {
	publicDM := rg.Group("/auto-dm")
	publicDM.GET("/unsubscribe/:token", c.GetDMPreference)
	publicDM.POST("/unsubscribe/:token", c.PublicUnsubscribeDM)

	group := rg.Group("/automations")
	group.Use(middleware.Auth())
	group.GET("", c.List)
	group.PUT("/:type", c.Update)
	group.POST("/:type/toggle", c.Toggle)
	group.PATCH("/:type/execution-mode", c.UpdateExecutionMode)
	group.GET("/runtime-status", c.RuntimeStatus)

	reply := rg.Group("/auto-replies")
	reply.Use(middleware.Auth())
	reply.GET("/drafts", c.ListReplyDrafts)
	reply.POST("/drafts/generate", c.GenerateReplyDraft)
	reply.PATCH("/drafts/:id", c.UpdateReplyDraft)
	reply.POST("/drafts/:id/rewrite", c.RewriteReplyDraft)
	reply.POST("/drafts/:id/approve", c.ApproveReplyDraft)
	reply.POST("/drafts/:id/reject", c.RejectReplyDraft)
	reply.POST("/drafts/:id/retry", c.RetryReplyDraft)

	dm := rg.Group("/auto-dm")
	dm.Use(middleware.Auth())
	dm.GET("/overview", c.DMOverview)
	dm.GET("/tasks", c.ListDMTasks)
	dm.GET("/recipients", c.ListDMRecipientRules)
	dm.GET("/recipients/imports", c.ListDMRecipientImports)
	dm.POST("/recipients/import/preview", c.PreviewDMRecipientRulesImport)
	dm.POST("/recipients/import", c.ImportDMRecipientRules)
	dm.PATCH("/recipient-rules/:id", c.UpdateDMRecipientRule)
	dm.POST("/recipient-rules/bulk", c.BulkUpdateDMRecipientRules)
	dm.POST("/tasks/:id/approve", c.ApproveDMTask)
	dm.PATCH("/tasks/:id", c.UpdateDMTask)
	dm.POST("/tasks/:id/block", c.BlockDMTask)
	dm.POST("/tasks/:id/retry", c.RetryDMTask)
	dm.DELETE("/tasks/:id", c.DeleteDMTask)
	dm.POST("/tasks/:id/recipient-rule", c.SetDMRecipientRule)

	radar := rg.Group("/exposure-radar")
	radar.Use(middleware.Auth())
	radar.POST("/drafts", c.CreateExposureRadarCommentDraft)
	radar.PATCH("/drafts/:id", c.UpdateCommentDraft)
	radar.POST("/drafts/:id/rewrite", c.RewriteCommentDraft)
	radar.POST("/drafts/:id/feedback", c.CreateCommentFeedback)
	radar.POST("/drafts/:id/approve", c.ApproveCommentTask)
	radar.POST("/drafts/:id/reject", c.RejectCommentDraft)
	radar.POST("/drafts/:id/handled", c.MarkCommentTaskHandled)
	radar.GET("/manual-records", c.ListExposureRadarManualRecords)
	radar.POST("/manual-records", c.UpsertExposureRadarManualRecord)
	radar.GET("/people", c.ListExposureRadarPeople)

	// Deprecated compatibility routes for legacy automations and historical queue links.
	comment := rg.Group("/auto-comment")
	comment.Use(middleware.Auth(), middleware.DeprecatedRoute("auto-comment", "/api/v1/exposure-radar/drafts"))
	comment.GET("/targets", c.ListCommentTargets)
	comment.POST("/targets", c.CreateCommentTarget)
	comment.POST("/targets/bulk-import", c.BulkImportCommentTargets)
	comment.POST("/targets/suggest", c.SuggestCommentTargets)
	comment.POST("/targets/:id/generate", c.GenerateCommentDraft)
	comment.PATCH("/targets/:id", c.UpdateCommentTargetStatus)
	comment.DELETE("/targets/:id", c.DeleteCommentTarget)
	comment.GET("/tasks", c.ListCommentTasks)
	comment.GET("/analytics", c.CommentAnalytics)
	comment.POST("/tasks/:id/approve", c.ApproveCommentTask)
	comment.POST("/tasks/:id/quote-post", c.QueueCommentQuotePost)
	comment.PATCH("/tasks/:id", c.UpdateCommentDraft)
	comment.DELETE("/tasks/:id", c.DeleteCommentDraft)
	comment.POST("/tasks/:id/block", c.BlockCommentTask)
	comment.POST("/tasks/:id/retry", c.RetryCommentTask)
	comment.POST("/tasks/:id/handled", c.MarkCommentTaskHandled)

	// Deprecated compatibility routes. New Exposure Radar draft clients should use /exposure-radar/drafts.
	comments := rg.Group("/auto-comments")
	comments.Use(middleware.Auth(), middleware.DeprecatedRoute("auto-comments", "/api/v1/exposure-radar/drafts"))
	comments.GET("/targets", c.ListCommentTargets)
	comments.POST("/targets", c.CreateCommentTarget)
	comments.POST("/targets/bulk-import", c.BulkImportCommentTargets)
	comments.POST("/targets/suggest", c.SuggestCommentTargets)
	comments.POST("/targets/:id/generate", c.GenerateCommentDraft)
	comments.POST("/exposure-radar-drafts", c.CreateExposureRadarCommentDraft)
	comments.PATCH("/targets/:id", c.UpdateCommentTargetStatus)
	comments.DELETE("/targets/:id", c.DeleteCommentTarget)
	comments.GET("/drafts", c.ListCommentTasks)
	comments.GET("/analytics", c.CommentAnalytics)
	comments.PATCH("/drafts/:id", c.UpdateCommentDraft)
	comments.POST("/drafts/:id/rewrite", c.RewriteCommentDraft)
	comments.DELETE("/drafts/:id", c.DeleteCommentDraft)
	comments.POST("/drafts/:id/feedback", c.CreateCommentFeedback)
	comments.POST("/drafts/:id/approve", c.ApproveCommentTask)
	comments.POST("/drafts/:id/quote-post", c.QueueCommentQuotePost)
	comments.POST("/drafts/:id/reject", c.RejectCommentDraft)
	comments.POST("/drafts/:id/handled", c.MarkCommentTaskHandled)
}
