services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: octo_agent

  backend:
    build:
      context: ../..
      dockerfile: deploy/docker/backend.Dockerfile
    restart: always

  api-front:
    build:
      context: ../..
      dockerfile: deploy/docker/frontend.Dockerfile
    restart: always

  admin-front:
    build:
      context: ../..
      dockerfile: deploy/docker/frontend.Dockerfile
    restart: always
