api:
  host: "0.0.0.0"
  port: 10001
admin:
  host: "0.0.0.0"
  port: 10002
mysql:
  # 数据库配置： 用户名:密码@(ip:端口)/库名？超时设置
  data_source: "root:root123456@tcp(127.0.0.1:3306)/octo_dev?timeout=10s&readTimeout=10s&writeTimeout=10s&charset=utf8mb4&parseTime=true"
  max_idle_conns: 10
  max_open_conns: 100
  max_lifetime: 3600
  max_idletime: 1800
log:
  level: "debug"
  encoding: "json"
  api_output_path: "logs/api.log"
  admin_output_path: "logs/admin.log"
  max_size: 100
  max_backups: 30
  max_age: 7
  compress: true
