api:
  host: "0.0.0.0"
  port: 10001
admin:
  host: "0.0.0.0"
  port: 10002
mysql:
  data_source: "TODO_MYSQL_DSN"
  max_idle_conns: 10
  max_open_conns: 100
  max_lifetime: 3600
  max_idletime: 1800
log:
  level: "debug"
  encoding: "json"
  api_output_path: "logs/api.log"
  admin_output_path: "logs/admin.log"
  max_size: 100
  max_backups: 30
  max_age: 7
  compress: true
